

CREATE SEQUENCE answers_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 6100 NO CYCLE;
CREATE SEQUENCE drivers_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 7 NO CYCLE;
CREATE SEQUENCE questions_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 35 NO CYCLE;
CREATE SEQUENCE surveys_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 4 NO CYCLE;
CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 370 NO CYCLE;

CREATE TABLE drivers(id INTEGER DEFAULT(nextval('drivers_id_seq')) PRIMARY KEY, drivers_name VARCHAR);
CREATE TABLE surveys(id INTEGER DEFAULT(nextval('surveys_id_seq')) PRIMARY KEY, "name" VARCHAR, created_time TIMESTAMP DEFAULT(current_localtimestamp()) NOT NULL, modified_time TIMESTAMP DEFAULT(current_localtimestamp()) NOT NULL, "cycle" VARCHAR);
CREATE TABLE users(id INTEGER DEFAULT(nextval('users_id_seq')) PRIMARY KEY, username VARCHAR NOT NULL, email VARCHAR);
CREATE TABLE questions(id INTEGER DEFAULT(nextval('questions_id_seq')) PRIMARY KEY, questions VARCHAR, surveys_id INTEGER NOT NULL, drivers_id INTEGER NOT NULL, qcode VARCHAR, FOREIGN KEY (surveys_id) REFERENCES surveys(id), FOREIGN KEY (drivers_id) REFERENCES drivers(id));
CREATE TABLE answers(id INTEGER DEFAULT(nextval('answers_id_seq')) PRIMARY KEY, user_id INTEGER NOT NULL, questions_id INTEGER NOT NULL, answers VARCHAR, "comments" VARCHAR, created_time TIMESTAMP DEFAULT(current_localtimestamp()) NOT NULL, modified_time TIMESTAMP DEFAULT(current_localtimestamp()) NOT NULL, FOREIGN KEY (questions_id) REFERENCES questions(id));




